#配置mysql数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simple_blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    table: flyway_schema_history_blog
    out-of-order: true

#配置端口号
server:
  port: 8072